version: '3'

services:
  # Traefik Reverse-Proxy Service
  traefik:
    image: traefik:v2.4
    container_name: traefik-proxy
    restart: always  
    labels:
      - traefik.enable=true
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik

# Do not forget to 'docker network create traefik-proxy' before launch, and to add '--network traefik-proxy' to proxied containers.

networks:
  default:
    external:
      name: traefik-proxy
