[http.middlewares]
  [http.middlewares.https_redirect.redirectScheme]
    scheme = "https"
    permanent = true
  # middleware: http(s)://(www.) to  https://
  [http.middlewares.wwwtohttps.redirectregex]
    regex = "^https?://(?:www\\.)?(.+)"
    replacement = "https://${1}"
    permanent = true
  [http.middlewares.auth.basicAuth]
    usersFile = "/etc/traefik/auth/traefik.password"
#[[tls.certificates]]
#  certFile = "/etc/traefik/ssl/quesmed.com.crt"
#  keyFile = "/etc/traefik/ssl/quesmed.com.key"

[http.routers.dashboard]
  rule = "Host(`monitor.mitrasinovic.co.uk`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
  service = "api@internal"
  middlewares = "auth"