[http.middlewares]
  [http.middlewares.https_redirect.redirectScheme]
    scheme = "https"
    permanent = true
  # middleware: http(s)://(www.) to  https://
  [http.middlewares.wwwtohttps.redirectregex]
    regex = "^https?://(?:www\\.)?(.+)"
    replacement = "https://${1}"
    permanent = true