[entryPoints.web]
  address = ":80"

[entryPoints.websecure]
  address = ":443"

[api]
  dashboard = true

[http.routers.my-api]
  rule = "Host(`monitor.mitrasinovic.co.uk`)"
  service = "api@internal"
  middlewares = ["auth"]

[http.middlewares]
  [http.middlewares.auth.basicAuth]
    usersFile = "etc/traefik/auth/traefik.password"

[certificatesresolvers.letsencrypt.acme]
  tlschallenge = true
  email = "smig88@gmail.com"
  storage = "/etc/traefik/acme.json"
[providers.docker]
  useBindPortIP = true
  exposedByDefault = false
  network = "traefik-proxy"
[providers.file]
  filename = "/etc/traefik/custom.toml"
